### ISSUE TITLE
是不是描述错了qaq

### ISSUE THREAD

**Issue by CuteLittleSky** [lijinhong11/MoreFlags#1]
![image](https://github.com/lijinhong11/MoreFlags/assets/62592731/f1020bc4-70ca-49c3-831e-2b6d34b0059d)
允许的时候苦力怕不能破坏方块 禁止的时候苦力怕可以破坏方块

另外我看在\plugins\Bentobox\flags也有一个配置文件 应该改哪个呢

**Comment by lijinhong11** [comment]
嘶 我不确定（描述确实得改）
等会修修 另外bbox那个配置文件我不确定有没有关系

**Comment by lijinhong11** [comment]
看一下1.0.1
